services:
  - type: web
    name: wait-time-api
    env: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://dasdivyadarshan_db_user:BcKktOKcX3o53Rzw@cluster0.a99djwz.mongodb.net/waitclarity?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: supersecretkey
      - key: GEMINI_API_KEY
        value: AIzaSyAyX9tBQkqH3ytCrgDSbeRSMxAKxQpPUTw
      - key: FRONTEND_URL
        value: https://wait-a-min-2zdy.vercel.app
